name: Commit pipeline
run-name: ${{ github.actor }} made a commit

on:
  push:
    branches:
      - ftr/*

jobs:
  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: check-editorconfig-existence
        if: ${{ hashFiles('.editorconfig') == '' }}
        run: echo '.editorconfig exists'

      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  pylint:
    runs-on: ubuntu20.04
    steps:
      - uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc <directory_name>

  black:
    runs-on: ubuntu22.04
    steps:
      - uses: psf/black@stable
