name: Commit pipeline
run-name: ${{ github.actor }} made a commit

on:
  push:
    branches:
      - ftr/*

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check-editorconfig-existence
        if: ${{ hashFiles('.editorconfig') == '' }}
        run: echo '.editorconfig exists'

      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: cclauss/GitHub-Action-for-pylint@0.7.0

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable

  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .

  unit-test:
    runs-on: ubuntu-latest
    working-directory: ./app
    env:
      PYTHON_VERSION: 3.10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
      - run: pip install -r requirements.txt
      - run: cd app
      - run: python -m unittest
